# Website settings
url: "https://elifefirat.github.io" # the base hostname & protocol for your site (e.g. http://example.com)
baseurl: "Horizon" # the subpath of your site (e.g. /blog)
title: "Elif E. Firat" # the name of your site

# User settings
name: Elif E. Firat
about: PhD Candidate in Information Visualization
email: "elif.firat[at]nottingham.ac.uk"
github: ""
gitlab: ""
linkedin: ""
twitter: ""

# Asset settings
picture: picture.jpg
qr-code: qrcode.png
# background-video: background.mp4
# background-video-thumbnail: background-thumbnail.jpg
background-image: wallpaperflare.com_wallpaper(1).jpg
